# Block message with swear
BlockSwear: false

# Allow Operators to swear
AllowOPSwear: false

# Message sent to player when swear
# If you don't want send any message, just leave it empty
SwearMessage: "&4Don't swear!"





# ATENTION
# CONTENT BELOW DOES NOT LOOK NICE

# Swears, disallowed words
# Use as
#    - swear: cen**red
# (you can use colors &4)
# Otherwise swear will be replaced by ***
# 
# NOTE: Put censored words between apostrophes
Blacklist:
- noob: 'n**b'
- idiot: 'id**t'
- ass: 'a**'
- penis: 'pen*s'
- vagina: 'vag**a'
- fuck: 'f**k'
- dick: 'd**k'
- pussy: 'p***y'
- stupid: 'st*pid'
- nerd: 'n**d'
- stfu: 's***'
- wtf: 'wt*'
- htf: 'ht*'
- anus: 'a***'
- arse: 'a***'
- arsehole: 'a***'
- asshole: 'a***'
- ahole: 'a***'
- butt: 'b**t'
- bitch: 'b**ch'
- crap: 'cr*p'
- bastard: 'b*stard'
- boobs: 'b**bs'
- shit: 'sh*t'
- piss: 'p*ss'
- dildo: 'd*ldo'
- fuckwit: 'f*ckw*t'
- cunt: 'c*nt'
- creampie: 'cr**mpie'
- fingeryourself: 'F*ng*r yo*rs*lf'
- jackoff: 'J*ck *ff'
- wackoff: 'W*ck *ff'
- sex: 's*x'
- porn: 'p**n'
- shag: 's**g'
- fagg: 'f*gg'
- feck: 'f*ck'
- flamer: 'fl*m*r'
- moron: 'm*ron'

# CZ / SK / PL
- kurw: 'k*r*'
- jeb: 'j*b'
- pic: 'p*c'
- debil: 'd*b*l'
- kokot: 'k*k*t'
- curak: 'c*r*k'
- cholera: 'ch*lera'
- chuj: 'ch*j'
- kutas: 'k*tas'
- cipa: 'c*pa'
- cipka: 'c*pka'
- kurde: 'k*rde'
- pizd: 'p*zd'
- suk: 's*k'
- cuk: 'c*k'
- dupa: 'd*pa'
- dupek: 'd*pek'
- dziwk: 'dz*wk'
- devk: 'd*vk'
- huj: 'h*j'
- chuj: 'ch*j'
- rit: 'r*t'
- prdel: 'prd*l'
- bozaj: 'b*zaj'

# Words containing blacklisted words, but are enabled
Whitelist:
- ' badass '
- ' as '
- ' _jeb '
- ' jeb_ '
